name: "unify"
version: "0.2.3"
description: "An implementation of logical unification for dart and flutter based on the algorithm by Ruzicka und Privara."
homepage: "https://github.com/welopment/unify"
environment:
  sdk: ">=2.7.0 <3.0.0"

enable-experiment:
  - non-nullable
  - extension-methods

dependencies:
  unification: ^0.1.0

dev_dependencies:
  pedantic: ^1.0.0
