name: "unify"
version: "0.1.6"
description: "An implementation of logical unification for dart and flutter based on the algorithm by Ruzicka und Privara."
homepage: "https://github.com/welopment/unify"
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  unification: ^0.1.0

dev_dependencies:
  #test: ^1.6.3
  pedantic: ^1.0.0
